controller:
  adminUser: "admin"
  adminPassword: "admin@123"
  installPlugins:
    - prometheus:2.2.1
    - cloudbees-disk-usage-simple:178.v1a_4d2f6359a_8
    - kubernetes:3971.v94b_4c914ca_75

  jenkinsUriPrefix: "/jenkins"

  ingress:
    enabled: true
    apiVersion: networking.k8s.io/v1
    annotations: 
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-port: '80'
      alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
      alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
      alb.ingress.kubernetes.io/success-codes: '200'
      alb.ingress.kubernetes.io/healthy-threshold-count: '2'
      alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
      alb.ingress.kubernetes.io/group.name: alb.group
      alb.ingress.kubernetes.io/group.order: '1'
       
    
    paths: 
      - backend:
          service: 
            name: jenkins
            port:
              number: 8080
        path: "/jenkins"  
        pathType: Prefix  

   
persistence:
  enabled: false

serviceAccountAgent:  
  create: true
