server:
 
  global:
    scrape_interval: 10s


serverFiles:
  prometheus.yml:
    
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
            - prometheus-server.kube-system.svc.cluster.local:80
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: 
            - kube-state-metrics.kube-system.svc.cluster.local:8080
      - job_name: prometheus
        static_configs:
          - targets:
            - prometheus-node-exporter.kube-system.svc.cluster.local:9100 

  persistentVolume:
    enabled: false



# alertmanager:
#   enabled: false

# kube-state-metrics:
#   enabled: false

# prometheus-node-exporter:
#   enabled: false
    
    rbac:
    pspEnabled: true

# prometheus-pushgateway:
#   enabled: false

  

    