variable "cluster_endpoint" {}
variable "cluster_token" {}
variable "cluster_certificate" {}
variable "alb_serviceaccount" {}
variable "account_id" {}
variable "alb_namespace" {}
variable "cluster_name" {}
variable "alb_policy_name" {}
variable "identity_oidc_issuer" {}
variable "aws_iam_openid_connect_provider" {}
variable "alb_ingress_name" {}
variable "alb_ingress_repo" {}
variable "alb_chart" {}