name: Static Test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run Checkov Action
      uses: bridgecrewio/checkov-action@master
      with:
        directory: modules
        quiet: true
        soft_fail: true
        framework: terraform
